name: Build EXE File

on:
  schedule:
    - cron: '0 0 * * 0'  # Uruchamia się w każdą niedzielę o północy
  push:
    branches: [main]     # Uruchamia się przy każdym pushu na main
  workflow_dispatch:     # Pozwala na ręczne uruchomienie

jobs:
  build:
    runs-on: windows-latest  # Używa najnowszego Windowsa
    
    steps:
    # Krok 1: Pobranie kodu
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Krok 2: Instalacja Pythona
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    # Krok 3: Instalacja zależności
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        .\installResources.ps1
    
    # Krok 4: Budowanie EXE
    - name: Build EXE file
      run: pyinstaller --onefile --noconsole converter.py
    
    # Krok 5: Udostępnienie pliku
    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: converter-app
        path: dist/converter.exe